services:
  - type: web
    name: discord-music-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: COOKIE_PATH
        value: cookies/cookie.txt
